version: 2
jobs:
  build:
    working_directory: ~/danger-js
    docker:
      - image: node:7
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run: yarn
      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/danger-js/node_modules
            - ~/.cache/yarn/
      - run: yarn add danger
      - run: yarn danger -- run --dangerfile dangerfile.circle.js --text-only
